# Generated by Django 5.0.2 on 2025-03-29 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/%d/')),
                ('file_size', models.IntegerField(default=0)),
                ('document_type', models.CharField(choices=[('original', 'Original'), ('merged', 'Merged PDF'), ('split', 'Split PDF'), ('compressed', 'Compressed PDF'), ('converted', 'Converted Document'), ('edited', 'Edited PDF'), ('secured', 'Secured PDF')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('merge', 'Merge PDFs'), ('split', 'Split PDF'), ('compress', 'Compress PDF'), ('convert_to', 'Convert To PDF'), ('convert_from', 'Convert From PDF'), ('rotate', 'Rotate PDF'), ('add_page_numbers', 'Add Page Numbers'), ('add_watermark', 'Add Watermark'), ('remove_pages', 'Remove Pages'), ('protect', 'Protect PDF'), ('unlock', 'Unlock PDF'), ('sign', 'Sign PDF'), ('ocr', 'OCR PDF')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
                ('input_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_input', to='pdf_tools.processeddocument')),
                ('output_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_output', to='pdf_tools.processeddocument')),
            ],
            options={
                'verbose_name_plural': 'Document Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_limit', models.IntegerField(default=104857600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
